### ISSUE TITLE
Support sub-styles reusage across same sheet.

### ISSUE THREAD

**Issue by lllShamanlll** [Jarzka/stylefy#2]
It would be nice to be able to reuse styles across same sheet.
i.e.
```clojure
(def control-style {::stylefy/sub-styles
                    {:button { ... }
                     :fixed-button (merge :button { ... })}})
```

**Comment by Jarzka** [comment]
Would be nice to have indeed.

Is there a reason not to create a separate style of the button? If so, I guess the button is only going to exist inside of control-style, right?

**Comment by kwladyka** [comment]
Use `(let [button {...}]
{...})`

**Comment by Jarzka** [comment]
let should be good solution here. I think we can close this issue.
