### ISSUE TITLE
custom stylefy definitions don't work in custom tag styles

### ISSUE THREAD

**Issue by nijk** [Jarzka/stylefy#20]
I can't seem to get media queries to work in conjunction with custom tag styles. This is necessary for global level cascading responsive behaviour used in conjunction with `rem` units 
e.g. `html { font-size: ... }`.

Example:
```
(stylefy/tag "div" {:background "yellow"
                    ::stylefy/media {{:min-width "1025px"} {:border "1px solid red"}}})
```

![screen shot 2018-04-17 at 16 01 00](https://user-images.githubusercontent.com/1615460/38878513-07013dd0-4259-11e8-8eff-2f02226def07.png)

**Comment by Jarzka** [comment]
Hi

Thanks for the bug report. I believe stylefy/tag simply does not support ::stylefy/media property. It should be implemented.

I can probably fix this in a week.

**Comment by nijk** [comment]
Thanks for the quick response.

That's good to know - I'm currently evaluating if we can keep using this library.

**Comment by Jarzka** [comment]
After doing a bit of debugging, I'm not even sure if this is a bug of missing feature, since stylefy/tag and stylefy/class were never designed to support custom stylefy definitions (media queries, modes etc.). These little utilities are used to simply generate a class or tag selector with CSS properties.

Sure, it would still be nice to define media queries, modes etc. for tags and custom classes so I'm still looking for adding support for it sometime in the near future. Right now, I'm going to fix the other issues you mentioned and release a bug fix.

**Comment by nijk** [comment]
Hey @Jarzka have you had any more thoughts on adding support for this request?

**Comment by Jarzka** [comment]
Hi

Sorry, I have been a bit busy with me life recently. However, I've got a plenty amount of time on the weekend so let's see if I can make some progress with this. :)

**Comment by nijk** [comment]
I know that feeling...

Thanks :) I appreciate it

**Comment by Jarzka** [comment]
I just released version 1.5.0-beta1 in which this missing feature has been added. Can you please test it?

**Comment by nijk** [comment]
Of course, it'll be my pleasure :)

**Comment by nijk** [comment]
Actually, I don't see version `1.5.0-beta1` [on the releases page](https://github.com/Jarzka/stylefy/releases), I guess that's just GitHub caching the page, but would you mind double checking?

**Comment by Jarzka** [comment]
The releases page has now been updated. However, you can test the new beta version simply by using the following dependency in the project.clj
`[stylefy "1.3.0-beta1"]`

**Comment by nijk** [comment]
Ah, I didn't realise that was possible - what magic makes that work?

**Comment by Jarzka** [comment]
The library and all of its versions are released on Clojars (https://clojars.org/). When you define stylefy as a dependency in your project.clj, it will be downloaded from Clojars by Leiningen build tool.

**Comment by nijk** [comment]
Thank you for the explanation :) if you hadn't already guessed Clojure(Script) is not my usually my thing

**Comment by nijk** [comment]
It works beautifully for the use case I've raised the ticket for 👍

**Comment by Jarzka** [comment]
Great to hear that! I will release this as 1.5.0 in a few days if no problems are found.

**Comment by Jarzka** [comment]
1.5.0 has now been released. This is the same version as the beta, as I did not find any problems with its changes. I think this issue can now be closed.
