### ISSUE TITLE
Non public function calls in Stylefy 1.10.0

### ISSUE THREAD

**Issue by jarnovayrynen** [Jarzka/stylefy#32]
When compiling Stylefy 1.10.0 with Figwheel, we get several warning of non public functions being called by the implementation:

WARNING: var: stylefy.impl.cache/cache-key-styles is not public at line 111 resources/public/js/out/stylefy/impl/dom.cljs
WARNING: var: stylefy.impl.conversion/class-selector is not public at line 159 resources/public/js/out/stylefy/impl/dom.cljs
WARNING: var: stylefy.impl.dom/save-style! is not public at line 60 resources/public/js/out/stylefy/impl/styles.cljs
WARNING: var: stylefy.impl.dom/style-by-hash is not public at line 143 resources/public/js/out/stylefy/impl/styles.cljs
WARNING: var: stylefy.impl.dom/update-dom is not public at line 176 resources/public/js/out/stylefy/impl/styles.cljs
WARNING: var: stylefy.impl.dom/save-style! is not public at line 60 resources/public/js/out/stylefy/impl/styles.cljs
WARNING: var: stylefy.impl.dom/style-by-hash is not public at line 143 resources/public/js/out/stylefy/impl/styles.cljs
WARNING: var: stylefy.impl.dom/update-dom is not public at line 176 resources/public/js/out/stylefy/impl/styles.cljs

**Comment by K1ll3rF0x** [comment]
Seems to me that they are just warnings by newer figwheel. I don't get any compilation errors.

**Comment by jarnovayrynen** [comment]
Yes it compiles so this is not so urgent.


Sent from mobile.

Toni Dahl <notifications@github.com<mailto:notifications@github.com>> kirjoitti 21.11.2018 kello 14.06:


Seems to me that they are just warnings by newer figwheel. I don't get any compilation errors.

**Comment by Jarzka** [comment]
Should be fixed now in 1.10.1.

**Comment by jarnovayrynen** [comment]
Thanks, cool.
