### ISSUE TITLE
Update Node package from 0.0.1 to 1.14.1

### ISSUE THREAD

**Issue by codereport** [Jarzka/stylefy#42]
https://www.npmjs.com/package/stylefy

You can see that Node package needs to be updated.

**Comment by Jarzka** [comment]
The node package you linked is a completely different library: github.com/stylefy/stylefy

I have never released any Node package. I publish stylefy to Clojars.

**Comment by codereport** [comment]
My mistake. I am a Clojure(script) beginner and have very litter frontend experience. I forked https://github.com/clojurecraft/cljs-starter and am trying to use your `stylefy`. 

...

Realized my mistake, i was trying to modify the `package.json` instead of the `shadow-cljs.edn` file. Working now! 💯
