### ISSUE TITLE
modes nested in medias

### ISSUE THREAD

**Issue by paintparty** [Jarzka/stylefy#46]
Is it currently possible to do this? I couldn't get it to work...

```Clojure
(use-style {::stylefy/media {{:max-width "699px"} {::stylefy/mode {:hover :red}}}})
```

Use case is I would like to apply a certain hover state, but only at a specific breakpoint.
Thanks!

**Comment by Jarzka** [comment]
Yes, this should be possible. There is also an example of this in the codebase: 

https://github.com/Jarzka/stylefy/blob/24584f8c527833d7f7f6dae2bddda1aa68d3043d/examples/src/stylefy/examples/hoverbox.cljs#L29

Your code looks correct. Can you give me a full of example how you use it and what is the generated CSS output?

**Comment by paintparty** [comment]
Now looking at this again ... I see the error in my example code^.

`{:hover :red}` should be `{:hover {:color :red}}`.

You are right, this works as expected. Thank you for the link to example in codebase, very helpful!

**Comment by Jarzka** [comment]
Good to hear the problem is solved.
