### ISSUE TITLE
Warnings on Figwheel build

### ISSUE THREAD

**Issue by paintparty** [Jarzka/stylefy#47]
Thanks again for adding the new features to Stylefy!

Just a heads up about warnings I'm getting from Figwheel. I'm using `figwheel-main "0.2.3"` and I see these when I run `lein fig:build`.

I'm pretty sure these are only unsightly warnings and do not affect the functionality of Stylefy. 

<img width="896" alt="Screen Shot 2020-06-10 at 10 11 50 PM" src="https://user-images.githubusercontent.com/1106506/84578371-7394c880-ad79-11ea-8154-30303bfe9820.png">
<img width="901" alt="Screen Shot 2020-06-05 at 6 44 41 PM" src="https://user-images.githubusercontent.com/1106506/84578390-a939b180-ad79-11ea-844e-b873ac6fe7c5.png">

**Comment by Jarzka** [comment]
I got the same warning when developing stylefy with Figwheel. `read-string` and `walk` are called with fully qualified namespace and they work when running the code. Thus, I'm not sure why Figwheel raises this warning.

**Comment by Jarzka** [comment]
Requiring seems to fix this problem. A fix for this will be included in the next release.
